name: CI - Python

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "fix/**"
      - "release/**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint (flake8)
        run: |
          . .venv/bin/activate
          if command -v flake8 >/dev/null 2>&1; then flake8 .; else echo "flake8 not installed, skip"; fi

      - name: Test (pytest)
        run: |
          . .venv/bin/activate
          if command -v pytest >/dev/null 2>&1; then pytest; else echo "pytest not installed, skip"; fi
